In [2]:
import numpy as np
from numpy.linalg import inv

# Linear Dynamics
$$\dot{x} = A\vec{x} + B\vec{u} \\
 \vec{y} = C\vec{x}$$

$\vec{x}$ is the state variables. $v_{x}, v_{y}$ is world linear velocity of the robot in m/s, $\omega$ is the angular velocity of the robot around the z-axis in rad/s.
$$
\vec{x} = \begin{bmatrix}
v_{x} \\ 
v_{y} \\
\omega_{z}
\end{bmatrix}
$$

$\vec{u}$ is the input vector. $\omega_{iFL}, \omega_{iFR}, \omega_{iBL}, \omega_{iBR}$ is commanded angular velocity of the front left, front right, back left, back right wheels of the robot (will refer to those positions for the remainder).
$$
\vec{u} = \begin{bmatrix}
\omega_{iFL} \\
\omega_{iFR} \\
\omega_{iBL} \\
\omega_{iBR}
\end{bmatrix}
$$

$\vec{y}$ is the measured observation vector. $\omega_{oFL},\omega_{oFR},\omega_{oBL},\omega_{oBR}$ is the angular wheel velocity for wheels of the robot in rad/s. $\omega_{gyro}$ is the angular velocity of the robot measured by the gyro in rad/s.

$$
\vec{y} = \begin{bmatrix}
\omega_{oFL} \\
\omega_{oFR} \\
\omega_{oBL} \\
\omega_{oBR} \\
\omega_{\text{gyro}}
\end{bmatrix}
$$

## Bot to Wheel Conversion

We need to make a transformation from the robot reference frame to the wheel reference frame
$r_{FL}, r_{FR}, r_{BL}, r_{BR}$ is the wheel radius in m.

$\theta_{FL}, \theta_{FR}, \theta_{BL}, \theta_{BR}$ is the angle offset from the center in rads.

$l_{FL}, l_{FR}, l_{BL}, l_{BR}$ is the distance to center in m.

$$
    \textbf{T}_{Wheel} = 
    \begin{bmatrix}
        sin(\theta_{FL})/r_{FL} & -cos(\theta_{FL})/r_{FL} & -l_{FL}/r_{FL} \\
        sin(\theta_{FR})/r_{FR} & -cos(\theta_{FR})/r_{FR} & -l_{FR}/r_{FR} \\
        sin(\theta_{BL})/r_{BL} & -cos(\theta_{BL})/r_{BL} & -l_{BL}/r_{BL} \\
        sin(\theta_{BR})/r_{BR} & -cos(\theta_{BR})/r_{BR} & -l_{BR}/r_{BR} \\
    \end{bmatrix}
$$

In [3]:
r = np.full((4,1),0.0245)
theta_deg = np.array([[30, 150, 225, 315]]).T
theta_rads = np.radians(theta_deg)
l = np.full((4,1),0.085)
T_wheel =  -1/r * -np.concatenate((np.sin(theta_rads), np.cos(theta_rads), l), axis = 1) 
print(T_wheel)

[[ 20.40816327  35.34797566   3.46938776]
 [ 20.40816327 -35.34797566   3.46938776]
 [-28.86150127 -28.86150127   3.46938776]
 [-28.86150127  28.86150127   3.46938776]]


## Wheel to Bot Conversion

Pseudo-inverse of $T_{Wheel}$ is the $T_{Bot}$
$$
    \textbf{T}_{Bot} = \textbf{T}^{\dagger}_{Wheel}
$$

In [4]:
T_bot = np.linalg.pinv(T_wheel)
print(T_bot)

[[ 0.01014823  0.01014823 -0.01014823 -0.01014823]
 [ 0.00848705 -0.00848705 -0.00692965  0.00692965]
 [ 0.08442216  0.08442216  0.05969548  0.05969548]]


## Robot Velocity to Wheel Velocity Example

In [5]:
v_example = np.array([1, 1, 0]).T
v_wheel_example = T_wheel*v_example
print(v_wheel_example)

[[ 20.40816327  35.34797566   0.        ]
 [ 20.40816327 -35.34797566   0.        ]
 [-28.86150127 -28.86150127   0.        ]
 [-28.86150127  28.86150127   0.        ]]


# Kalman Filter

In [6]:
process_noise = 0.05 # State noise for unmodeled influences, TODO unclear where is comes from
encoder_sampling_freq = 100 # Hz
encoder_noise_rads = np.radians(0.068) # rads for AS5047P encoder RMS output noise (1 sigma)
encoder_noise = encoder_noise_rads/(1/encoder_sampling_freq) # rads/s TODO unclear if this is valid
gryo_noise_noise_density = 0.014  # deg/s/√Hz for BMI085 Noise density (typ.)
gyro_sampling_freq = 100 # Hz
gyro_noise = np.radians(gryo_noise_noise_density) * np.sqrt(gyro_sampling_freq) # in rad/s

intial_covariance = 0.1 # Picked at random TODO

print(encoder_noise)
print(gyro_noise)

0.11868238913561441
0.002443460952792061
